import type { IconType } from "react-icons";
import { CgCPlusPlus } from "react-icons/cg";
import {
  FaAndroid,
  FaAngular,
  FaAws,
  FaBootstrap,
  FaCss3,
  FaDocker,
  FaGitAlt,
  FaHtml5,
  FaJava,
  FaJenkins,
  FaJs,
  FaLinux,
  FaMarkdown,
  FaNodeJs,
  FaPhp,
  FaPython,
  FaReact,
  FaRust,
  FaSass,
  FaWordpress,
  FaYarn,
} from "react-icons/fa";
import { GrMysql, GrOracle } from "react-icons/gr";
import {
  SiC,
  SiCloudfoundry,
  SiGnubash,
  SiGo,
  SiHibernate,
  SiJquery,
  SiJupyter,
  SiKotlin,
  SiMongodb,
  SiNpm,
  SiScikitlearn,
  SiSpring,
  SiSpringboot,
  SiTerraform,
  SiTypescript,
} from "react-icons/si";
import { VscVscode } from "react-icons/vsc";

export const skillIcons: Record<string, IconType> = {
  FaPython,
  FaJava,
  CgCPlusPlus,
  SiC,
  SiGnubash,
  FaJs,
  SiTypescript,
  SiKotlin,
  SiGo,
  FaRust,
  FaPhp,
  FaHtml5,
  FaCss3,
  FaSass,
  FaMarkdown,
  SiSpring,
  SiSpringboot,
  FaReact,
  FaAngular,
  FaNodeJs,
  SiJquery,
  FaBootstrap,
  FaWordpress,
  SiHibernate,
  SiScikitlearn,
  GrMysql,
  SiOracle: GrOracle,
  SiMongodb,
  FaGitAlt,
  FaDocker,
  SiNpm,
  FaYarn,
  FaJenkins,
  FaAndroid,
  FaAws,
  SiCloudfoundry,
  FaLinux,
  SiJupyter,
  SiVisualstudiocode: VscVscode,
  SiTerraform,
};
