import type { IconType } from "react-icons";
import { CgCPlusPlus } from "react-icons/cg";
import {
  FaAndroid,
  FaAngular,
  FaAws,
  FaBootstrap,
  FaCss3,
  FaDocker,
  FaGitAlt,
  FaHtml5,
  FaJava,
  FaJenkins,
  FaJs,
  FaLinux,
  FaMarkdown,
  FaNodeJs,
  FaPhp,
  FaPython,
  FaReact,
  FaRust,
  FaSass,
  FaWordpress,
  FaYarn,
} from "react-icons/fa";
import { GrMysql, GrOracle } from "react-icons/gr";
import {
  SiC,
  SiCloudfoundry,
  SiExpress,
  SiGithubactions,
  SiGnubash,
  SiGo,
  SiHibernate,
  SiJquery,
  SiJupyter,
  SiKotlin,
  SiKubernetes,
  SiMongodb,
  SiNpm,
  SiRedis,
  SiScikitlearn,
  SiServerless,
  SiSpring,
  SiSpringboot,
  SiTerraform,
  SiTypescript,
} from "react-icons/si";
import { VscVscode } from "react-icons/vsc";

export const skillIcons: Record<string, IconType> = {
  FaPython,
  FaJava,
  CgCPlusPlus,
  SiC,
  SiGnubash,
  FaJs,
  SiTypescript,
  SiKotlin,
  SiGo,
  FaRust,
  FaPhp,
  FaHtml5,
  FaCss3,
  FaSass,
  FaMarkdown,
  SiSpring,
  SiSpringboot,
  FaReact,
  FaAngular,
  FaNodeJs,
  SiExpress,
  SiJquery,
  FaBootstrap,
  FaWordpress,
  SiHibernate,
  SiScikitlearn,
  SiServerless,
  GrMysql,
  SiOracle: GrOracle,
  SiMongodb,
  SiRedis,
  FaGitAlt,
  FaDocker,
  SiKubernetes,
  SiNpm,
  FaYarn,
  FaJenkins,
  SiGithubactions,
  FaAndroid,
  FaAws,
  SiCloudfoundry,
  FaLinux,
  SiJupyter,
  SiVisualstudiocode: VscVscode,
  SiTerraform,
};

export function resolveSkillIcon(icon: string, label: string): IconType {
  const Icon = skillIcons[icon];
  if (!Icon) {
    throw new Error(`Missing skill icon "${icon}" for "${label}"`);
  }
  return Icon;
}
